global:
  image:
    repository: ghcr.io/vfo018/intact-kafka-tools
    tag: "0.2.1"
    pullPolicy: IfNotPresent
  kafkaBootstrapServers: "51.178.36.152:9092"

mitigator:
  enabled: true
  env:
    MODE: "mitigator"
    IN_TOPIC: "mmt-reports"
    OUT_TOPIC: "ulanc-response-mitigator"
    GROUP_ID: "stix-mitigator"
    CLIENT_ID: "stix-mitigator"
    AUTO_OFFSET_RESET: "latest"
    KEEP_ORIGINAL_BUNDLE_ID: "0"
    DECIDED_BY: "ulanc-mitigator"
    DEFAULT_CONFIDENCE: "0.9"
    BLOCK_DURATION_SEC: "3600"
    PRINT_IO_JSON: "1"
    PRINT_SUMMARY: "1"
    MAX_JSON_CHARS: "12000"

attackSimulator:
  enabled: false

responseConsumer:
  enabled: true
  env:
    MODE: "response_consumer"
    TOPIC: "ulanc-response-mitigator"
    GROUP_ID: "response-consumer"
    AUTO_OFFSET_RESET: "latest"
